src/models/folders/views.py
from collections import defaultdict
from flask import Blueprint, request, render_template, session, redirect, url_for, flash
import src.models.users.decorators as user_decorators
from src.common.decorators import check_confirmed
from src.models.uploaders.uploader import Uploader

folder_blueprint = Blueprint('folders', __name__)


@folder_blueprint.route('/', methods=['GET', 'POST'])
@user_decorators.requires_login
@check_confirmed
def folders():
    root = Uploader.create_root(session['user_id'])

    if request.method == 'POST':
        folder_name = request.form['folder_name']
        parent = request.form['parent']

        ancestor = Uploader.find_ancestor(parent, session['user_id'])

        folder = Uploader(
            user_id=session['user_id'],
            upload_type='folder',
            file_name=folder_name,
            parent=parent,
        )

        folder.ancestors = ancestor.ancestors
        folder.ancestors.append(ancestor.file_name)

        folder.save_to_mongo()

        flash("Folder created successfully", 'success')
        return redirect(url_for('.folder_list_for_id', parent_id=folder.get_id))

    return redirect(url_for('.folder_list_for_ancestor', parent_name=root.file_name))


@folder_blueprint.route('/<string:parent_id>')
@user_decorators.requires_login
@check_confirmed
def folder_list_for_id(parent_id):
    user_files = Uploader.all(session['user_id'], parent_id)
    ancestor = Uploader.find_ancestor(parent_id, session['user_id'])
    quick_folder = Uploader.quick_folder_access(session['user_id'])

    files_map = defaultdict(list)

    for user_file in user_files:
        files_map[user_file.upload_type].append(user_file)

    return render_template('uploaders/index.jinja2',
                           files=files_map,
                           parent_id=parent_id,
                           routes=ancestor.ancestors,
                           present_folder=ancestor.file_name,
                           quick_folder=quick_folder)


@folder_blueprint.route('/<string:parent_name>/ancestor')
@user_decorators.requires_login
@check_confirmed
def folder_list_for_ancestor(parent_name):
    ancestor = Uploader.find_ancestor_by_name(parent_name, session['user_id'])
    user_files = Uploader.all(session['user_id'], ancestor.get_id)
    quick_folder = Uploader.quick_folder_access(session['user_id'])

    files_map = defaultdict(list)

    for user_file in user_files:
        files_map[user_file.upload_type].append(user_file)

    return render_template('uploaders/index.jinja2',
                           files=files_map,
                           parent_id=ancestor.get_id,
                           routes=ancestor.ancestors,
                           present_folder=ancestor.file_name,
                           quick_folder=quick_folder)


@folder_blueprint.route('/<string:parent_id>/search')
@user_decorators.requires_login
@check_confirmed
def folder_search(parent_id):
    query = request.args['query']
    user_files = Uploader.search(session['user_id'], parent_id, query)
    ancestor = Uploader.find_ancestor(parent_id, session['user_id'])
    quick_folder = Uploader.quick_folder_access(session['user_id'])

    files_map = defaultdict(list)

    for user_file in user_files:
        files_map[user_file.upload_type].append(user_file)

    return render_template('uploaders/index.jinja2',
                           files=files_map,
                           query=query,
                           parent_id=ancestor.get_id,
                           routes=ancestor.ancestors,
                           present_folder=ancestor.file_name,
                           quick_folder=quick_folder)


@folder_blueprint.route('/<string:file_id>/delete', methods=['POST'])
@user_decorators.requires_login
@check_confirmed
def delete(file_id):
    upload_type = Uploader.remove_file(file_id, session['user_id'])

    if upload_type == 'folder':
        flash("Folder successfully deleted", 'success')
    else:
        flash("File successfully deleted", 'success')

    return redirect(request.referrer)

src/models/users/views.py
import datetime
from flask import Blueprint, request, url_for, render_template, flash, session
from werkzeug.utils import redirect
import src.models.users.errors as UserErrors
import src.models.users.decorators as user_decorators
from src.common.decorators import check_confirmed
from src.common.email import send_email, send_email_with_mailgun
from src.models.uploaders.uploader import Uploader
from src.models.users.token import generate_confirmation_token, confirm_token
from src.models.users.user import User

user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.login_succeed(email, password):
                flash('You were successfully logged in', 'success')
                return redirect(url_for('folders.folders'))

        except UserErrors.UserError as e:
            return render_template("users/login.jinja2",
                                   error=e.message,
                                   title='Login')

    return render_template("users/login.jinja2", title='Login')   # Send the user an error if login is invalid


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            user = User.register_user(email, password)
            if user:
                Uploader.create_root(user.get_id)
                token = generate_confirmation_token(user.email)

                confirm_url = url_for('users.confirm_email', token=token, _external=True)
                html = render_template('users/activate.html', confirm_url=confirm_url)

                subject = "Please confirm your email"

                send_email(user.email, subject, html)

                flash('A confirmation email has been sent via email.', 'success')
                # return redirect(url_for(".login_user"))
                return redirect(url_for(".unconfirmed"))

        except UserErrors.UserError as e:
            return render_template("users/register.jinja2",
                                   error=e.message,
                                   title='Register')

    return render_template("users/register.jinja2", title='Register')   # Send the user an error if login is invalid


@user_blueprint.route('/confirm/<token>')
def confirm_email(token):
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is invalid or has expired.', 'danger')

    user = User.find_by_email(email)

    if user.confirmed:
        flash('Account already confirmed. Please login.', 'success')
        return redirect(url_for('.login_user'))
    else:
        user.confirmed = True
        user.confirmed_on = datetime.datetime.now()
        user.save_to_db()

        User.login(user)

        flash('You have confirmed your account. Thanks!', 'success')
    return redirect(url_for('folders.folders'))


@user_blueprint.route('/<string:user_id>/uploads')
@user_decorators.requires_login
@check_confirmed
def user_uploads(user_id):
    user_files = Uploader.all(user_id)

    return render_template('uploaders/index.jinja2', files=user_files, title='Uploads')


@user_blueprint.route('/unconfirmed')
@user_decorators.requires_login
def unconfirmed():
    if User.current_user().confirmed:
        return redirect('folders.folders')

    # flash('Please confirm your account!', 'warning')
    return render_template('users/unconfirmed.jinja2')


@user_blueprint.route('/resend')
@user_decorators.requires_login
def resend_confirmation():
    current_user = User.current_user()

    token = generate_confirmation_token(current_user.email)
    confirm_url = url_for('.confirm_email', token=token, _external=True)
    html = render_template('users/activate.html', confirm_url=confirm_url)
    subject = "Please confirm your email"
    send_email(current_user.email, subject, html)

    flash('A new confirmation email has been sent.', 'success')
    return redirect(url_for('users.unconfirmed'))


@user_blueprint.route('/logout')
def logout_user():
    User.logout()

    return redirect(url_for('home'))  # .home for redirecting in current view

src/templates/alerts.jinja2
{% if success %}
    <div class="alert alert-success alert-dismissable">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        {{ success }}
    </div>

{% elif error %}
    <div class="alert alert-danger alert-dismissable">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        {{ error }}
    </div>
{% endif%}

{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category if category else 'success' }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

src/templates/base.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if title %}
        <title>{{ title }} - Ife's Cloud</title>
    {% else %}
        <title>Ife's Cloud</title>
    {% endif %}

    {% include 'html_dependencies.jinja2' %}
</head>
<body>
    <div class="wrapper">
        <!-- Sidebar Holder -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>Ife's Cloud</h3>
                <strong>Ife</strong>
            </div>

            <ul class="list-unstyled components">
                <li class="quick-access">
                    <i class="fas fa-folder fa-1x"></i> Quick Folder Access
                </li>
                {% if session['user_id'] and quick_folder %}
                    {% for folder in quick_folder %}
                        <li>
                            <a href="{{ url_for('folders.folder_list_for_ancestor', parent_name=folder.file_name) }}">
                                <i class="far fa-folder fa-1x"></i>
                                {{ folder.file_name }}
                            </a>
                        </li>
                    {% endfor %}
                {% endif %}
            </ul>
        </nav>


        <div id="content">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn">
                            <i class="glyphicon glyphicon-align-left"></i>
                            <span>Toggle Sidebar</span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            {% if session['email'] %}
                                <li><a href="{{ url_for('folders.folders') }}">Home <span class="glyphicon glyphicon-home"></span></a></li>
                                <li><a href="#">FAQ's <span class="glyphicon glyphicon-question-sign"></span></a></li>
                                <li><a href="{{ url_for('users.logout_user') }}">Log out <span class="glyphicon glyphicon-log-out"></span></a></li>
                            {% else %}
                                <li><a href="{{ url_for('users.register_user') }}">Sign Up <span class="glyphicon glyphicon-user"></span></a></li>
                                <li><a href="{{ url_for('users.login_user') }}">Login <span class="glyphicon glyphicon-log-in"></span></a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>

            {% include 'alerts.jinja2' %}

            {% block content %}

            {% endblock %}
        </div>
    </div>

<!-- Modal -->
<div class="modal fade" id="newFolder" role="dialog">
    <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Create new folder</h4>
        </div>

        <div class="modal-body">
            {% include 'uploaders/snippets/new-folder.jinja2' %}
        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </div>

    </div>
</div>
</body>
</html>

src/templates/home.jinja2
{% extends "base.jinja2" %}
{% block content %}
   <a href="{{ url_for('users.user_uploads', user_id=user.get_id) }}" class="btn btn-primary"><span class="glyphicon glyphicon-eye-open"></span> My Files</a>

{% endblock %}

src/templates/html_dependencies.jinja2
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/web-fonts-with-css/css/fontawesome-all.css') }}" >
<script rel="stylesheet" type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.3.1.min.js') }}"></script>
<script rel="stylesheet" type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
<script rel="stylesheet" type="text/javascript" src="{{ url_for('static', filename='js/custom.js') }}"></script>