src/models/folders/views.py
from collections import defaultdict
from flask import Blueprint, request, render_template, session, redirect, url_for, flash
import src.models.users.decorators as user_decorators
from src.common.decorators import check_confirmed
from src.models.uploaders.uploader import Uploader

folder_blueprint = Blueprint('folders', __name__)


@folder_blueprint.route('/', methods=['GET', 'POST'])
@user_decorators.requires_login
@check_confirmed
def folders():
    root = Uploader.create_root(session['user_id'])

    if request.method == 'POST':
        folder_name = request.form['folder_name']
        parent = request.form['parent']

        ancestor = Uploader.find_ancestor(parent, session['user_id'])

        folder = Uploader(
            user_id=session['user_id'],
            upload_type='folder',
            file_name=folder_name,
            parent=parent,
        )

        folder.ancestors = ancestor.ancestors
        folder.ancestors.append(ancestor.file_name)

        folder.save_to_mongo()

        flash("Folder created successfully", 'success')
        return redirect(url_for('.folder_list_for_id', parent_id=folder.get_id))

    return redirect(url_for('.folder_list_for_ancestor', parent_name=root.file_name))


@folder_blueprint.route('/<string:parent_id>')
@user_decorators.requires_login
@check_confirmed
def folder_list_for_id(parent_id):
    user_files = Uploader.all(session['user_id'], parent_id)
    ancestor = Uploader.find_ancestor(parent_id, session['user_id'])
    quick_folder = Uploader.quick_folder_access(session['user_id'])

    files_map = defaultdict(list)

    for user_file in user_files:
        files_map[user_file.upload_type].append(user_file)

    return render_template('uploaders/index.jinja2',
                           files=files_map,
                           parent_id=parent_id,
                           routes=ancestor.ancestors,
                           present_folder=ancestor.file_name,
                           quick_folder=quick_folder)


@folder_blueprint.route('/<string:parent_name>/ancestor')
@user_decorators.requires_login
@check_confirmed
def folder_list_for_ancestor(parent_name):
    ancestor = Uploader.find_ancestor_by_name(parent_name, session['user_id'])
    user_files = Uploader.all(session['user_id'], ancestor.get_id)
    quick_folder = Uploader.quick_folder_access(session['user_id'])

    files_map = defaultdict(list)

    for user_file in user_files:
        files_map[user_file.upload_type].append(user_file)

    return render_template('uploaders/index.jinja2',
                           files=files_map,
                           parent_id=ancestor.get_id,
                           routes=ancestor.ancestors,
                           present_folder=ancestor.file_name,
                           quick_folder=quick_folder)


@folder_blueprint.route('/<string:parent_id>/search')
@user_decorators.requires_login
@check_confirmed
def folder_search(parent_id):
    query = request.args['query']
    user_files = Uploader.search(session['user_id'], parent_id, query)
    ancestor = Uploader.find_ancestor(parent_id, session['user_id'])
    quick_folder = Uploader.quick_folder_access(session['user_id'])

    files_map = defaultdict(list)

    for user_file in user_files:
        files_map[user_file.upload_type].append(user_file)

    return render_template('uploaders/index.jinja2',
                           files=files_map,
                           query=query,
                           parent_id=ancestor.get_id,
                           routes=ancestor.ancestors,
                           present_folder=ancestor.file_name,
                           quick_folder=quick_folder)


@folder_blueprint.route('/<string:file_id>/delete', methods=['POST'])
@user_decorators.requires_login
@check_confirmed
def delete(file_id):
    upload_type = Uploader.remove_file(file_id, session['user_id'])

    if upload_type == 'folder':
        flash("Folder successfully deleted", 'success')
    else:
        flash("File successfully deleted", 'success')

    return redirect(request.referrer)

src/models/uploaders/views.py
import os
from flask import Blueprint, request, render_template, session, send_from_directory, redirect, url_for, flash
from werkzeug.utils import secure_filename
import src.models.users.decorators as user_decorators
from src.definitions import ROOT_PATH
from src.models.uploaders.uploader import Uploader
from src.models.users.user import User

upload_blueprint = Blueprint('uploader', __name__)

APP_ROOT = ROOT_PATH


@upload_blueprint.route('/new/<string:parent_id>', methods=['GET', 'POST'])
@user_decorators.requires_login
def upload(parent_id):
    user = User.find_by_email(session['email'])
    target = os.path.join(APP_ROOT, 'public/uploads/{}'.format(user.get_id))
    quick_folder = Uploader.quick_folder_access(session['user_id'])

    if not os.path.isdir(target):
        os.mkdir(target)

    if request.files.getlist("file_upload"):
        for file in request.files.getlist("file_upload"):
            if file and Uploader.allowed_file(file.filename):
                file_name = secure_filename(file.filename).lower()
                destination = "/".join([target, file_name])
                file.save(destination)

                doc = Uploader(
                    user_id=user.get_id,
                    file_name=file_name,
                    ext_name=Uploader.ext_name(file_name),
                    parent=parent_id
                )

                doc.save_to_mongo()

            else:
                flash('File name: {} with extension {} is prohibited.'.format(file.filename,
                                                                              Uploader.ext_name(file.filename)),
                      'warning')
                return redirect(request.referrer)

        flash('File successfully uploaded', 'success')

        return redirect(url_for('folders.folder_list_for_id', parent_id=parent_id))

    return render_template('uploaders/upload.jinja2', parent_id=parent_id, quick_folder=quick_folder)


@upload_blueprint.route('/<string:user_id>/view/<string:file_id>')
def send_file(user_id, file_id):
    file = Uploader.find_one(file_id, user_id)
    return send_from_directory(Uploader.path(user_id), file.file_name)


@upload_blueprint.route('/<string:user_id>/<string:file_id>/download')
def download_file(user_id, file_id):
    file = Uploader.find_one(file_id, user_id)
    return send_from_directory(Uploader.path(user_id),
                               file.file_name,
                               as_attachment=True)

src/templates/uploaders/file_types/3-dot-menu.jinja2
<div class="card-menu">
    {% if file.new %}
        <span class="label label-danger">New</span>
    {% else %}
        <span class="created_text">{{ file.created_at.strftime("%a, %b %y")}} </span>
    {% endif %}
    <div class="dropup">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="three-dot"></div>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
            {% if file.upload_type != 'folder' %}
                <li>
                    <a href="{{ url_for('uploader.download_file', user_id=file.user_id, file_id=file.get_id) }}">
                        <span class="glyphicon glyphicon-download-alt"></span>  Download</a>
                </li>
                <li>
                    <a target="_blank" href="{{ url_for('uploader.send_file', user_id=file.user_id, file_id=file.get_id) }}">
                        <span class="glyphicon glyphicon-eye-open"></span>  View</a>
                </li>
            {% endif %}
            <li>
                <a href="{{ url_for('folders.delete', file_id=file.get_id) }}" class="delete-link">
                    <span class="glyphicon glyphicon-trash"></span>  Delete</a>
            </li>
        </ul>
    </div>
</div>

src/templates/uploaders/file_types/display_files.jinja2
{% if file.ext_name in ['.jpg', '.png', '.jpeg', '.gif'] %}
    <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6">
        {% include 'uploaders/file_types/image.jinja2' %}
    </div>
{% elif file.ext_name in ['.pdf'] %}
    <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6">
        {% include 'uploaders/file_types/pdf.jinja2' %}
    </div>
{% elif file.ext_name in ['.docx', '.dotx'] %}
    <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6">
        {% include 'uploaders/file_types/word.jinja2' %}
    </div>
{% elif file.upload_type in ['folder'] %}
    <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6">
        {% include 'uploaders/file_types/folder.jinja2' %}
    </div>
{% endif %}

src/templates/uploaders/file_types/folder.jinja2
<div class="card">
    {% include 'uploaders/file_types/3-dot-menu.jinja2' %}
    <a href="{{ url_for('folders.folder_list_for_ancestor', parent_name=file.file_name) }}">
        <div class="folder-container">
            <i class="far fa-folder fa-3x file-folder"></i>
        </div>
    </a>

    <div class="card-container">
        <p class="folder-file-name" title="{{ file.file_name }}">{{ file.file_name }}</p>
    </div>
</div>

src/templates/uploaders/file_types/image.jinja2
<div class="card">
   {% include 'uploaders/file_types/3-dot-menu.jinja2' %}

    <div class="image-container">
        <img src="{{ url_for('uploader.send_file', user_id=file.user_id, file_id=file.get_id) }}" alt="Avatar">
    </div>
    <div class="card-container">
        <p class="file-name" title="{{ file.file_name }}">{{ file.file_name }}</p>
    </div>
</div>

src/templates/uploaders/file_types/pdf.jinja2
<div class="card">
    {% include 'uploaders/file_types/3-dot-menu.jinja2' %}
    <div class="image-container">
        <i class="far fa-file-pdf fa-5x pdf-file"></i>
    </div>
    <div class="card-container">
        <p class="file-name" title="{{ file.file_name }}">{{ file.file_name }}</p>
    </div>
</div>

src/templates/uploaders/file_types/word.jinja2
<div class="card">
    {% include 'uploaders/file_types/3-dot-menu.jinja2' %}
    <div class="image-container">
        <i class="far fa-file-word fa-5x word-file"></i>
    </div>
    <div class="card-container">
        <p class="file-name" title="{{ file.file_name }}">{{ file.file_name }}</p>
    </div>
</div>