src/models/folders/views.py
from collections import defaultdict
from flask import Blueprint, request, render_template, session, redirect, url_for, flash
import src.models.users.decorators as user_decorators
from src.common.decorators import check_confirmed
from src.models.uploaders.uploader import Uploader

folder_blueprint = Blueprint('folders', __name__)


@folder_blueprint.route('/', methods=['GET', 'POST'])
@user_decorators.requires_login
@check_confirmed
def folders():
    root = Uploader.create_root(session['user_id'])

    if request.method == 'POST':
        folder_name = request.form['folder_name']
        parent = request.form['parent']

        ancestor = Uploader.find_ancestor(parent, session['user_id'])

        folder = Uploader(
            user_id=session['user_id'],
            upload_type='folder',
            file_name=folder_name,
            parent=parent,
        )

        folder.ancestors = ancestor.ancestors
        folder.ancestors.append(ancestor.file_name)

        folder.save_to_mongo()

        flash("Folder created successfully", 'success')
        return redirect(url_for('.folder_list_for_id', parent_id=folder.get_id))

    return redirect(url_for('.folder_list_for_ancestor', parent_name=root.file_name))


@folder_blueprint.route('/<string:parent_id>')
@user_decorators.requires_login
@check_confirmed
def folder_list_for_id(parent_id):
    user_files = Uploader.all(session['user_id'], parent_id)
    ancestor = Uploader.find_ancestor(parent_id, session['user_id'])
    quick_folder = Uploader.quick_folder_access(session['user_id'])

    files_map = defaultdict(list)

    for user_file in user_files:
        files_map[user_file.upload_type].append(user_file)

    return render_template('uploaders/index.jinja2',
                           files=files_map,
                           parent_id=parent_id,
                           routes=ancestor.ancestors,
                           present_folder=ancestor.file_name,
                           quick_folder=quick_folder)


@folder_blueprint.route('/<string:parent_name>/ancestor')
@user_decorators.requires_login
@check_confirmed
def folder_list_for_ancestor(parent_name):
    ancestor = Uploader.find_ancestor_by_name(parent_name, session['user_id'])
    user_files = Uploader.all(session['user_id'], ancestor.get_id)
    quick_folder = Uploader.quick_folder_access(session['user_id'])

    files_map = defaultdict(list)

    for user_file in user_files:
        files_map[user_file.upload_type].append(user_file)

    return render_template('uploaders/index.jinja2',
                           files=files_map,
                           parent_id=ancestor.get_id,
                           routes=ancestor.ancestors,
                           present_folder=ancestor.file_name,
                           quick_folder=quick_folder)


@folder_blueprint.route('/<string:parent_id>/search')
@user_decorators.requires_login
@check_confirmed
def folder_search(parent_id):
    query = request.args['query']
    user_files = Uploader.search(session['user_id'], parent_id, query)
    ancestor = Uploader.find_ancestor(parent_id, session['user_id'])
    quick_folder = Uploader.quick_folder_access(session['user_id'])

    files_map = defaultdict(list)

    for user_file in user_files:
        files_map[user_file.upload_type].append(user_file)

    return render_template('uploaders/index.jinja2',
                           files=files_map,
                           query=query,
                           parent_id=ancestor.get_id,
                           routes=ancestor.ancestors,
                           present_folder=ancestor.file_name,
                           quick_folder=quick_folder)


@folder_blueprint.route('/<string:file_id>/delete', methods=['POST'])
@user_decorators.requires_login
@check_confirmed
def delete(file_id):
    upload_type = Uploader.remove_file(file_id, session['user_id'])

    if upload_type == 'folder':
        flash("Folder successfully deleted", 'success')
    else:
        flash("File successfully deleted", 'success')

    return redirect(request.referrer)

src/models/uploaders/views.py
import os
from flask import Blueprint, request, render_template, session, send_from_directory, redirect, url_for, flash
from werkzeug.utils import secure_filename
import src.models.users.decorators as user_decorators
from src.definitions import ROOT_PATH
from src.models.uploaders.uploader import Uploader
from src.models.users.user import User

upload_blueprint = Blueprint('uploader', __name__)

APP_ROOT = ROOT_PATH


@upload_blueprint.route('/new/<string:parent_id>', methods=['GET', 'POST'])
@user_decorators.requires_login
def upload(parent_id):
    user = User.find_by_email(session['email'])
    target = os.path.join(APP_ROOT, 'public/uploads/{}'.format(user.get_id))
    quick_folder = Uploader.quick_folder_access(session['user_id'])

    if not os.path.isdir(target):
        os.mkdir(target)

    if request.files.getlist("file_upload"):
        for file in request.files.getlist("file_upload"):
            if file and Uploader.allowed_file(file.filename):
                file_name = secure_filename(file.filename).lower()
                destination = "/".join([target, file_name])
                file.save(destination)

                doc = Uploader(
                    user_id=user.get_id,
                    file_name=file_name,
                    ext_name=Uploader.ext_name(file_name),
                    parent=parent_id
                )

                doc.save_to_mongo()

            else:
                flash('File name: {} with extension {} is prohibited.'.format(file.filename,
                                                                              Uploader.ext_name(file.filename)),
                      'warning')
                return redirect(request.referrer)

        flash('File successfully uploaded', 'success')

        return redirect(url_for('folders.folder_list_for_id', parent_id=parent_id))

    return render_template('uploaders/upload.jinja2', parent_id=parent_id, quick_folder=quick_folder)


@upload_blueprint.route('/<string:user_id>/view/<string:file_id>')
def send_file(user_id, file_id):
    file = Uploader.find_one(file_id, user_id)
    return send_from_directory(Uploader.path(user_id), file.file_name)


@upload_blueprint.route('/<string:user_id>/<string:file_id>/download')
def download_file(user_id, file_id):
    file = Uploader.find_one(file_id, user_id)
    return send_from_directory(Uploader.path(user_id),
                               file.file_name,
                               as_attachment=True)

src/templates/uploaders/index.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <ol class="breadcrumb">
        {% for route in routes %}
            <li><a href="{{ url_for('folders.folder_list_for_ancestor', parent_name=route) }}">
                <i class="far fa-folder fa-1x"></i> {{ route }}</a></li>
        {% endfor %}
        <li class="active">
            <a href="{{ url_for('folders.folder_list_for_ancestor', parent_name=present_folder) }}">
            <i class="far fa-folder fa-1x"></i> {{ present_folder }}
            </a>
        </li>
    </ol>

    <div class="page-header">
        <h1>Your files</h1>
        <div class="input-group header-options">
            <form class="form-inline" action="{{ url_for('folders.folder_search', parent_id=parent_id) }}">
                <div class="form-group">
                    <input type="text" class="form-control" id="search_folder" value="{{ query }}" name="query" placeholder="Enter file name">
                </div>
                <button type="submit" id="search_button" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
            </form>
            <div class="input-group-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#newFolder">
                        <span class="glyphicon glyphicon-plus"></span> New Folder
                    </button>
                    <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="caret"></span>
                        <span class="sr-only">Toggle Dropdown</span>
                    </button>
                    <ul class="dropdown-menu header-options-menu">
                        <li>
                            <a href="{{ url_for('uploader.upload', parent_id=parent_id) }}">
                                <i class="glyphicon glyphicon-upload"></i>
                                Upload
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    {% if files.folder %}
        <div class="page-header">
            <h4>Folders</h4>
        </div>
        <div class="row">
            {% for file in files.folder %}
                {% include 'uploaders/file_types/display_files.jinja2' %}
            {% endfor %}
        </div>
    {% endif %}

    {% if files.file %}
        {% if files.folder %}
            <div class="page-header">
                <h4>Files</h4>
            </div>
        {% endif %}
        <div class="row">
            {% for file in files.file %}
                {% include 'uploaders/file_types/display_files.jinja2' %}
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

src/templates/uploaders/upload.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="form-size">
        <form action="{{ url_for('uploader.upload', parent_id=parent_id) }}", method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label for="file_upload">Files</label>
                <input type="file" class="form-control" id="file_upload" name="file_upload" multiple />
            </div>

            <button type="submit" class="btn btn-success">Upload</button>
        </form>
    </div>
{% endblock %}